name: 掘金自动领取bugfix
on:
  # 手动执行
  workflow_dispatch:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: '0 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: 运行自动领取掘金bug
        run: |
          python auto_receive_bug.py '${{ secrets.COOKIE }}' '${{ secrets.WX_APP_ID }}' '${{ secrets.WX_APP_SECRET }}'  ${{ secrets.WX_COMPANY_ID }} '${{ secrets.WORKWX_WEBHOOK }}'
